server:
  port: 8080
  context-path: /api

spring:
  application:
    name: starnight-reactor
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/starnight
    username: postgres
    password: 123456
  data:
    # Redis
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 1
  # es
  elasticsearch:
    uris: http://localhost:9200
    username: elasticsearch
    password: 123456

  # 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# r2dbc 日志
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

# star-night 配置
starnight:
  # security
  security:
    ignores:
      - /api/user/login/**
      - /api/user/logout/**
      - /api/user/register/**